aws_region="us-east-1"
aws_profile="default"
image_repo_name="trailplanner"
source_backend_repo_name="trail-planner-backend"
source_lambda_repo_name="trail-planner-process-lambda"
source_repo_branch="main"
source_repo_owner="MasterCloudApps-Projects"
stack="terraform-trailplanner"