version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI --target development .
  post_build:
    commands:
      - echo Build completed and run tests on `date`
      - docker run -u root --name $CONTAINER_NAME-tests $REPOSITORY_URI /bin/bash -c "npm install"
      - echo Start database migration
      - docker run -e POSTGRES_USER=$RDS_DB_USERNAME -e POSTGRES_HOST=$RDS_HOST -e POSTGRES_PASSWORD=$RDS_DB_PASSWORD -e POSTGRES_DB=$RDS_DB_NAME -e POSTGRES_PORT=$RDS_DB_PORT -u root --name $CONTAINER_NAME-migration $REPOSITORY_URI /bin/bash -c "npm install | npm run typeorm migration:run -- -d ./typeOrm.config.ts"