version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
  build:
    commands:
      - echo Run lint and tests on `date`
      - npm run lint
      - npm run test
  post_build:
    commands:
      - echo Complete tests and lint on `date`
cache:
  paths:
    - node_modules