version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - n 18
      - npm i
      - npm run lint
  pre_build:
    commands:
      - npm i
      - npm run type-check
      # - npm run test:unit
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*"
  name: "dist"
  base-directory: dist

cache:
  paths:
    - /root/.npm/**/*